<a href="https://colab.research.google.com/github/kaynatmozammil/Data-Science-/blob/main/15_session_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 9, 12, 65, 56, 13, 55, 24, 63, 67, 14, 65, 44, 23, 10, 51])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[39, 58, 83, 15],
       [ 9, 18, 10, 39],
       [73, 92, 59, 75],
       [ 9, 89, 93, 38],
       [77, 79, 88, 51],
       [31, 72, 93, 47]])

In [ ]:
np.sort(a)[::-1]

array([97, 88, 77, 70, 67, 67, 61, 50, 44, 39, 32, 13,  7,  7,  7])

In [ ]:
np.sort(b,axis = 0)

array([[ 4, 39,  5, 12],
       [34, 65, 19, 48],
       [75, 85, 60, 54],
       [88, 92, 69, 58],
       [92, 96, 88, 80],
       [95, 97, 98, 88]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,676)

array([ 32,  88,  70,  67,  61,  13,   7,  44,  50,  39,  97,   7,  77,
        67,   7, 676])

In [ ]:
b

array([[88, 39, 69, 80],
       [75, 92, 60, 54],
       [92, 96,  5, 58],
       [ 4, 85, 19, 88],
       [95, 65, 98, 12],
       [34, 97, 88, 48]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[88., 39., 69., 80.,  1.],
       [75., 92., 60., 54.,  1.],
       [92., 96.,  5., 58.,  1.],
       [ 4., 85., 19., 88.,  1.],
       [95., 65., 98., 12.,  1.],
       [34., 97., 88., 48.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis = 1)

array([[88.        , 39.        , 69.        , 80.        ,  0.3030868 ],
       [75.        , 92.        , 60.        , 54.        ,  0.6922322 ],
       [92.        , 96.        ,  5.        , 58.        ,  0.65539535],
       [ 4.        , 85.        , 19.        , 88.        ,  0.70737827],
       [95.        , 65.        , 98.        , 12.        ,  0.17314318],
       [34.        , 97.        , 88.        , 48.        ,  0.15647896]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis= 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a

array([32, 88, 70, 67, 61, 13,  7, 44, 50, 39, 97,  7, 77, 67,  7])

In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis  = 0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis  = 1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([32, 88, 70, 67, 61, 13,  7, 44, 50, 39, 97,  7, 77, 67,  7])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  2,  3,  4, 10, 12, 13]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([32,  0,  0,  0,  0, 13,  7, 44, 50, 39,  0,  7,  0,  0,  7])

In [ ]:
np.where(a%2 == 0,0,a)


array([ 0,  0,  0, 67, 61, 13,  7,  0,  0, 39, 97,  7, 77, 67,  7])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([32, 88, 70, 67, 61, 13,  7, 44, 50, 39, 97,  7, 77, 67,  7])

In [ ]:
np.argmax(a)

10

In [ ]:
b

array([[88, 39, 69, 80],
       [75, 92, 60, 54],
       [92, 96,  5, 58],
       [ 4, 85, 19, 88],
       [95, 65, 98, 12],
       [34, 97, 88, 48]])

In [ ]:
np.argmax(b)

18

In [ ]:
np.argmax(b,axis = 0)

array([4, 5, 4, 3])

In [ ]:
np.argmax(b,axis = 1)

array([0, 1, 1, 3, 2, 1])

In [ ]:
a

array([32, 88, 70, 67, 61, 13,  7, 44, 50, 39, 97,  7, 77, 67,  7])

In [ ]:
# np.argmin
np.argmin(a)

6

In [ ]:
np.argmin(b)

12

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([ 9, 12, 65, 56, 13, 55, 24, 63, 67, 14, 65, 44, 23, 10, 51])

In [ ]:

np.cumsum(a)

array([  9,  21,  86, 142, 155, 210, 234, 297, 364, 378, 443, 487, 510,
       520, 571])

In [ ]:
b

array([[39, 58, 83, 15],
       [ 9, 18, 10, 39],
       [73, 92, 59, 75],
       [ 9, 89, 93, 38],
       [77, 79, 88, 51],
       [31, 72, 93, 47]])

In [ ]:
np.cumsum(b)

array([  39,   97,  180,  195,  204,  222,  232,  271,  344,  436,  495,
        570,  579,  668,  761,  799,  876,  955, 1043, 1094, 1125, 1197,
       1290, 1337])

In [ ]:
np.cumsum(b,axis =1)

array([[ 39,  97, 180, 195],
       [  9,  27,  37,  76],
       [ 73, 165, 224, 299],
       [  9,  98, 191, 229],
       [ 77, 156, 244, 295],
       [ 31, 103, 196, 243]])

In [ ]:
# np.cumprod
a

array([ 9, 12, 65, 56, 13, 55, 24, 63, 67, 14, 65, 44, 23, 10, 51])

In [ ]:
np.cumprod(a)

array([                  9,                 108,                7020,
                    393120,             5110560,           281080800,
                6745939200,        424994169600,      28474609363200,
           398644531084800,   25911894520512000, 1140123358902528000,
       7776093181048592384, 3973955515647717376, -242453512771481600])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([ 9, 12, 65, 56, 13, 55, 24, 63, 67, 14, 65, 44, 23, 10, 51])

In [ ]:
np.percentile(a,100)

67.0

In [ ]:
np.percentile(a,0)

9.0

In [ ]:
np.percentile(a,50)

44.0

In [ ]:
np.median(a)

44.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([ 9, 12, 65, 56, 13, 55, 24, 63, 67, 14, 65, 44, 23, 10, 51])

In [ ]:
np.histogram(a,bins=[0,70,100])

(array([15,  0]), array([  0,  70, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a

array([ 9, 12, 65, 56, 13, 55, 24, 63, 67, 14, 65, 44, 23, 10, 51])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([10])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([ 9, 12, 65, 56, 13, 55, 24, 63, 67, 14, 65, 44, 23, 10, 51])

In [ ]:
np.flip(a)

array([51, 10, 23, 44, 65, 14, 67, 63, 24, 55, 13, 56, 65, 12,  9])

In [ ]:
b

array([[39, 58, 83, 15],
       [ 9, 18, 10, 39],
       [73, 92, 59, 75],
       [ 9, 89, 93, 38],
       [77, 79, 88, 51],
       [31, 72, 93, 47]])

In [ ]:
np.flip(b,axis = 1)

array([[15, 83, 58, 39],
       [39, 10, 18,  9],
       [75, 59, 92, 73],
       [38, 93, 89,  9],
       [51, 88, 79, 77],
       [47, 93, 72, 31]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([334, 444,  65,  56,  13,  55,  24,  63,  67,  14,  65,  44,  23,
        10,  51])

In [ ]:
np.put(a,[0,1],[334,444])

In [ ]:
a

array([334, 444,  65,  56,  13,  55,  24,  63,  67,  14,  65,  44,  23,
        10,  51])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([334, 444,  65,  56,  13,  55,  24,  63,  67,  14,  65,  44,  23,
        10,  51])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals